principio_attivo("abacavir").
principio_attivo("abciximab").
principio_attivo("abiraterone").
principio_attivo("acarbosio").
principio_attivo("aceclofenac").
principio_attivo("acenocumarolo").
principio_attivo("acetazolamide").
principio_attivo("acetilcarnitina").
principio_attivo("acetilcisteina").
principio_attivo("aciclovir").
principio_attivo("acido_acetilsalicilico").
principio_attivo("acido_alendronico").
principio_attivo("acido_alginico").
principio_attivo("acido_aminolevulenico").
principio_attivo("acido_aminosalicilico").
principio_attivo("acido_ascorbico").
principio_attivo("acido_azelaico").
principio_attivo("acido_borico").
principio_attivo("acido_chenodesossicolico").
principio_attivo("acido_clodronico").
principio_attivo("acido_cromoglicico").
principio_attivo("acido_diatrizoico").
principio_attivo("acido_etacrinico").
principio_attivo("acido_folico").
principio_attivo("acido_fusidico").
principio_attivo("acido_gadobenico").
principio_attivo("acido_gadopentetico").
principio_attivo("acido_gadoterico").
principio_attivo("acido_ialuronico").
principio_attivo("acido_ibandronico").
principio_attivo("acido_idrossibutirrico").
principio_attivo("acido_iossaglico").
principio_attivo("acido_obeticolico").
principio_attivo("acido_pamidronico").
principio_attivo("acido_pipemidico").
principio_attivo("acido_risedronico").
principio_attivo("acido_salicilico").
principio_attivo("acido_spaglumico").
principio_attivo("acido_tranexamico").
principio_attivo("acido_undecilenico").
principio_attivo("acido_ursodesossicolico").
principio_attivo("acido_valproico").
principio_attivo("acido_zoledronico").
principio_attivo("acitretina").
principio_attivo("acth").
principio_attivo("adalimumab").
principio_attivo("adapalene").
principio_attivo("adefovir").
principio_attivo("adenosina").
principio_attivo("adrenalina").
principio_attivo("adrenergici").
principio_attivo("afatinib").
principio_attivo("aflibercept").
principio_attivo("agalsidase").
principio_attivo("alanil").
principio_attivo("albendazolo").
principio_attivo("albiglutide").
principio_attivo("albumina").
principio_attivo("alcaloidi").
principio_attivo("alchilamine").
principio_attivo("alcinonide").
principio_attivo("alemtuzumab").
principio_attivo("alfacalcidolo").
principio_attivo("alfuzosina").
principio_attivo("aliskiren").
principio_attivo("alitretinoina").
principio_attivo("alizapride").
principio_attivo("allopurinolo").
principio_attivo("almotriptan").
principio_attivo("aloperidolo").
principio_attivo("alprazolam").
principio_attivo("alprostadil").
principio_attivo("ambroxolo").
principio_attivo("amfenicoli").
principio_attivo("amfotericina").
principio_attivo("amifampridina").
principio_attivo("amifostina").
principio_attivo("amikacina").
principio_attivo("amine").
principio_attivo("aminochinoline").
principio_attivo("aminofillina").
principio_attivo("amiodarone").
principio_attivo("amisulpride").
principio_attivo("amitriptilina").
principio_attivo("amlodipina").
principio_attivo("ammonio").
principio_attivo("amorolfina").
principio_attivo("amoxicillina").
principio_attivo("ampicillina").
principio_attivo("anagrelide").
principio_attivo("anastrozolo").
principio_attivo("androgeni").
principio_attivo("anidulafungina").
principio_attivo("anilidi").
principio_attivo("antiaggreganti").
principio_attivo("antiandrogeni").
principio_attivo("antibiotici").
principio_attivo("anticolinergici").
principio_attivo("anticolinesterasici").
principio_attivo("antidepressivi").
principio_attivo("antidiarroici").
principio_attivo("antigene").
principio_attivo("antimicotici").
principio_attivo("antimicrobici").
principio_attivo("antipropulsivi").
principio_attivo("antipsoriasici").
principio_attivo("antisettici").
principio_attivo("antispastici").
principio_attivo("antistaminici").
principio_attivo("antitrombina").
principio_attivo("antivirali").
principio_attivo("antracicline").
principio_attivo("antrax").
principio_attivo("apparato").
principio_attivo("aprepitant").
principio_attivo("argatroban").
principio_attivo("aria").
principio_attivo("aripiprazolo").
principio_attivo("artenimolo").
principio_attivo("articaina").
principio_attivo("asenapina").
principio_attivo("asfotase").
principio_attivo("atazanavir").
principio_attivo("atenololo").
principio_attivo("atorvastatina").
principio_attivo("atosiban").
principio_attivo("atracurio").
principio_attivo("atropina").
principio_attivo("auranofin").
principio_attivo("avelumab").
principio_attivo("axitinib").
principio_attivo("azanidazolo").
principio_attivo("azatioprina").
principio_attivo("azelastina").
principio_attivo("azitromicina").
principio_attivo("aztreonam").
principio_attivo("bacampicillina").
principio_attivo("baclofene").
principio_attivo("bario").
principio_attivo("barnidipina").
principio_attivo("basiliximab").
principio_attivo("bazedoxifene").
principio_attivo("beclometasone").
principio_attivo("bedaquilina").
principio_attivo("belatacept").
principio_attivo("benazepril").
principio_attivo("bendamustina").
principio_attivo("bendazac").
principio_attivo("benralizumab").
principio_attivo("benzalconio").
principio_attivo("benzamidi").
principio_attivo("benzidamina").
principio_attivo("benzilpenicillina").
principio_attivo("benzocaina").
principio_attivo("benzoile").
principio_attivo("benzydamine").
principio_attivo("betabloccanti").
principio_attivo("betaina").
principio_attivo("betaistina").
principio_attivo("betametasone").
principio_attivo("betaxololo").
principio_attivo("bevacizumab").
principio_attivo("bexarotene").
principio_attivo("bezafibrato").
principio_attivo("bicalutamide").
principio_attivo("bifosfonati").
principio_attivo("biguanidi").
principio_attivo("bilastina").
principio_attivo("bimatoprost").
principio_attivo("bioflavonoidi").
principio_attivo("biotina").
principio_attivo("bisacodile").
principio_attivo("bisoprololo").
principio_attivo("bivalirudina").
principio_attivo("bleomicina").
principio_attivo("bmp-2").
principio_attivo("boceprevir").
principio_attivo("bornaprina").
principio_attivo("bortezomib").
principio_attivo("bosentan").
principio_attivo("bosutinib").
principio_attivo("brimonidina").
principio_attivo("brinzolamide").
principio_attivo("brivudina").
principio_attivo("brodalumab").
principio_attivo("brolucizumab").
principio_attivo("bromazepam").
principio_attivo("bromexina").
principio_attivo("bromocriptina").
principio_attivo("brotizolam").
principio_attivo("bucetina").
principio_attivo("budesonide").
principio_attivo("buflomedil").
principio_attivo("bupivacaina").
principio_attivo("buprenorfina").
principio_attivo("bupropione").
principio_attivo("buserelin").
principio_attivo("busulfano").
principio_attivo("butamirato").
principio_attivo("butilscopolamina").
principio_attivo("buxamina").
principio_attivo("cabazitaxel").
principio_attivo("cabergolina").
principio_attivo("caffeina").
principio_attivo("calcio").
principio_attivo("calcipotriolo").
principio_attivo("calcitriolo").
principio_attivo("canagliflozin").
principio_attivo("canakinumab").
principio_attivo("candesartan").
principio_attivo("cangrelor").
principio_attivo("canrenoato").
principio_attivo("capecitabina").
principio_attivo("capsaicina").
principio_attivo("captopril").
principio_attivo("carbamazepina").
principio_attivo("carbazocromo").
principio_attivo("carbetocina").
principio_attivo("carbocisteina").
principio_attivo("carbone").
principio_attivo("carboplatino").
principio_attivo("carfilzomib").
principio_attivo("carmustina").
principio_attivo("carteololo").
principio_attivo("carvedilolo").
principio_attivo("cascara").
principio_attivo("caspofungin").
principio_attivo("catridecagog").
principio_attivo("catumaxomab").
principio_attivo("cefaclor").
principio_attivo("cefalosporina").
principio_attivo("cefalosporine").
principio_attivo("cefalotina").
principio_attivo("cefamandolo").
principio_attivo("cefatrizina").
principio_attivo("cefazolina").
principio_attivo("cefditoren").
principio_attivo("cefepima").
principio_attivo("cefixima").
principio_attivo("cefodizima").
principio_attivo("cefonicid").
principio_attivo("cefoperazone").
principio_attivo("cefotaxima").
principio_attivo("cefpodoxima").
principio_attivo("cefprozil").
principio_attivo("ceftaroline").
principio_attivo("ceftazidima").
principio_attivo("ceftizoxima").
principio_attivo("ceftobiprolo").
principio_attivo("ceftolozane").
principio_attivo("ceftriaxone").
principio_attivo("cefuroxime").
principio_attivo("celecoxib").
principio_attivo("celiprololo").
principio_attivo("ceritinib").
principio_attivo("cetilpiridinio").
principio_attivo("cetirizina").
principio_attivo("cetrorelix").
principio_attivo("cetuximab").
principio_attivo("chinina").
principio_attivo("cianocobalamina").
principio_attivo("ciclobenzaprina").
principio_attivo("ciclopirox").
principio_attivo("ciclosporina").
principio_attivo("cidofovir").
principio_attivo("cilazapril").
principio_attivo("cilostazolo").
principio_attivo("cimetidina").
principio_attivo("cimicifugae").
principio_attivo("cinacalcet").
principio_attivo("cinnarizina").
principio_attivo("cinoxacina").
principio_attivo("ciprofloxacin").
principio_attivo("ciprofloxacina").
principio_attivo("ciproterone").
principio_attivo("cisatracurio").
principio_attivo("cisplatino").
principio_attivo("citalopram").
principio_attivo("citarabina").
principio_attivo("citicolina").
principio_attivo("claritromicina").
principio_attivo("clevidipine").
principio_attivo("clidinio").
principio_attivo("clindamicina").
principio_attivo("clobazam").
principio_attivo("clobetasolo").
principio_attivo("clobetasone").
principio_attivo("clofarabina").
principio_attivo("clofoctolo").
principio_attivo("clomifene").
principio_attivo("clomipramina").
principio_attivo("clonazepam").
principio_attivo("clonidina").
principio_attivo("cloperastina").
principio_attivo("clopidogrel").
principio_attivo("cloramfenicolo").
principio_attivo("clorazepato").
principio_attivo("clorexidina").
principio_attivo("clorfenamina").
principio_attivo("clormadinone").
principio_attivo("clormetina").
principio_attivo("clorochina").
principio_attivo("cloroprocaina").
principio_attivo("clorpromazina").
principio_attivo("clorpropamide").
principio_attivo("clortalidone").
principio_attivo("clortetraciclina").
principio_attivo("clostridiopeptidasi").
principio_attivo("clotiazepam").
principio_attivo("clotrimazolo").
principio_attivo("clozapina").
principio_attivo("cobamamide").
principio_attivo("cobicistat").
principio_attivo("cobimetinib").
principio_attivo("codeina").
principio_attivo("colecalciferolo").
principio_attivo("colestiramina").
principio_attivo("colestrano").
principio_attivo("colina").
principio_attivo("colistina").
principio_attivo("collagenase").
principio_attivo("condroitinsolfato").
principio_attivo("corifollitropina").
principio_attivo("corticosteroidi").
principio_attivo("corticosteroidi/antimicrobici/midriatici").
principio_attivo("crizotinib").
principio_attivo("cromoglicato").
principio_attivo("dabigatran").
principio_attivo("dacarbazina").
principio_attivo("daclizumab").
principio_attivo("danazolo").
principio_attivo("dantrolene").
principio_attivo("dapagliflozina").
principio_attivo("dapiprazolo").
principio_attivo("dapoxetina").
principio_attivo("daptomicina").
principio_attivo("darbepoetina").
principio_attivo("darunavir").
principio_attivo("deferoxamina").
principio_attivo("deflazacort").
principio_attivo("delapril").
principio_attivo("denosumab").
principio_attivo("deoxycholic").
principio_attivo("deprimenti").
principio_attivo("dequalinio").
principio_attivo("dermatan").
principio_attivo("desametasone").
principio_attivo("desclorfeniramina").
principio_attivo("desloratadina").
principio_attivo("desmopressina").
principio_attivo("desogestrel").
principio_attivo("desonide").
principio_attivo("desossimetasone").
principio_attivo("despantenolo").
principio_attivo("destrano").
principio_attivo("destrometorfano").
principio_attivo("dexibuprofene").
principio_attivo("dexmedetomidina").
principio_attivo("dexrazoxano").
principio_attivo("dextriferron").
principio_attivo("diazepam").
principio_attivo("dibromtirosina").
principio_attivo("dibutilcarboetilene").
principio_attivo("diclofenac").
principio_attivo("diclofenamide").
principio_attivo("diclorofenilcarbinolo").
principio_attivo("didanosina").
principio_attivo("didecildimetilammonio").
principio_attivo("dienogest").
principio_attivo("difenidramina").
principio_attivo("diflucortolone").
principio_attivo("difterite-epatite").
principio_attivo("difterite-hemophilus").
principio_attivo("difterite-pertosse-poliomielite-tetano").
principio_attivo("digossina").
principio_attivo("diidroergocriptina").
principio_attivo("diidroergotamina").
principio_attivo("diidroergotossina").
principio_attivo("diltiazem").
principio_attivo("dimethyl").
principio_attivo("dimetindene").
principio_attivo("dinoprostone").
principio_attivo("dinutuximab").
principio_attivo("diosmectite").
principio_attivo("diosmina").
principio_attivo("dipiridamolo").
principio_attivo("diprofillina").
principio_attivo("disopiramide").
principio_attivo("dispositivi").
principio_attivo("disulfiram").
principio_attivo("dobutamina").
principio_attivo("docetaxel").
principio_attivo("docusato").
principio_attivo("dolutegravir").
principio_attivo("domperidone").
principio_attivo("donepezil").
principio_attivo("dopamina").
principio_attivo("dornase").
principio_attivo("dorzolamide").
principio_attivo("dosulepina").
principio_attivo("doxazosina").
principio_attivo("doxiciclina").
principio_attivo("doxofillina").
principio_attivo("doxorubicina").
principio_attivo("dronedarone").
principio_attivo("droperidolo").
principio_attivo("drospirenone").
principio_attivo("duloxetina").
principio_attivo("dupilumab").
principio_attivo("dutasteride").
principio_attivo("ebastina").
principio_attivo("econazolo").
principio_attivo("eculizumab").
principio_attivo("edetati").
principio_attivo("efavirenz").
principio_attivo("efedrina").
principio_attivo("eletriptan").
principio_attivo("elettroliti").
principio_attivo("eliglustat").
principio_attivo("elosulfase").
principio_attivo("eltrombopag").
principio_attivo("emodialitici").
principio_attivo("emofiltrati").
principio_attivo("emostatici").
principio_attivo("emtricitabina").
principio_attivo("emtricitabine").
principio_attivo("enalapril").
principio_attivo("encefalite").
principio_attivo("enfuvirtide").
principio_attivo("enoxaparina").
principio_attivo("enoximone").
principio_attivo("entacapone").
principio_attivo("entecavir").
principio_attivo("eosina").
principio_attivo("eparina").
principio_attivo("eparinici").
principio_attivo("eparinoidi").
principio_attivo("epinastine").
principio_attivo("epirubicina").
principio_attivo("eplerenone").
principio_attivo("epoprostenolo").
principio_attivo("eprosartan").
principio_attivo("eptotermin").
principio_attivo("ergometrina").
principio_attivo("ergotamina").
principio_attivo("eritromicina").
principio_attivo("eritropoietina").
principio_attivo("erlotinib").
principio_attivo("ertapenem").
principio_attivo("esametazina").
principio_attivo("escitalopram").
principio_attivo("eslicarbazepina").
principio_attivo("esmololo").
principio_attivo("esomeprazolo").
principio_attivo("espettoranti").
principio_attivo("estradiolo").
principio_attivo("estramustina").
principio_attivo("estriolo").
principio_attivo("estrogeni").
principio_attivo("etambutolo").
principio_attivo("etamsilato").
principio_attivo("etanercept").
principio_attivo("etilefrina").
principio_attivo("etinilestradiolo").
principio_attivo("etofenamato").
principio_attivo("etonogestrel").
principio_attivo("etoposide").
principio_attivo("etoricoxib").
principio_attivo("etosuccimide").
principio_attivo("etravirina").
principio_attivo("evolocumab").
principio_attivo("exemestane").
principio_attivo("exenatide").
principio_attivo("ezetimibe").
principio_attivo("famciclovir").
principio_attivo("famotidina").
principio_attivo("felbinac").
principio_attivo("felodipina").
principio_attivo("fenformina").
principio_attivo("fenilefrina").
principio_attivo("fenitoina").
principio_attivo("fenobarbitale").
principio_attivo("fenofibrato").
principio_attivo("fenoldopam").
principio_attivo("fenolo").
principio_attivo("fenoterolo").
principio_attivo("fenotiazine").
principio_attivo("fenspiride").
principio_attivo("fentanil").
principio_attivo("fenticonazolo").
principio_attivo("ferro").
principio_attivo("ferumoxsil").
principio_attivo("fexofenadina").
principio_attivo("fibrati").
principio_attivo("fidaxomicina").
principio_attivo("filgrastim").
principio_attivo("finasteride").
principio_attivo("fitomenadione").
principio_attivo("flavossato").
principio_attivo("flecainide").
principio_attivo("florbetaben").
principio_attivo("flucitosina").
principio_attivo("flucloxacillina").
principio_attivo("fluconazolo").
principio_attivo("fludarabina").
principio_attivo("flufenazina").
principio_attivo("flumazenil").
principio_attivo("flumetasone").
principio_attivo("flunarizina").
principio_attivo("flunisolide").
principio_attivo("flunitrazepam").
principio_attivo("fluocinolone").
principio_attivo("fluocinonide").
principio_attivo("fluocortolone").
principio_attivo("fluoresceina").
principio_attivo("fluoro-18f-desossiglucosio").
principio_attivo("fluorochinoloni").
principio_attivo("fluorodopa").
principio_attivo("fluorometilcolina").
principio_attivo("fluorometolone").
principio_attivo("fluorouracile").
principio_attivo("fluoxetina").
principio_attivo("flupirtina").
principio_attivo("fluprednidene").
principio_attivo("flurazepam").
principio_attivo("flurbiprofene").
principio_attivo("flutamide").
principio_attivo("fluticasone").
principio_attivo("fluvastatina").
principio_attivo("follitropina").
principio_attivo("fondaparinux").
principio_attivo("formoterolo").
principio_attivo("fosamprenavir").
principio_attivo("foscarnet").
principio_attivo("fosfocreatina").
principio_attivo("fosfomicina").
principio_attivo("fosinopril").
principio_attivo("fotemustina").
principio_attivo("frovatriptan").
principio_attivo("fulvestrant").
principio_attivo("furosemide").
principio_attivo("fusafungina").
principio_attivo("gabapentin").
principio_attivo("gadobutrolo").
principio_attivo("gadoteridolo").
principio_attivo("gadoversetamide").
principio_attivo("galantamina").
principio_attivo("gallio-67ga-citrato").
principio_attivo("gallopamil").
principio_attivo("ganciclovir").
principio_attivo("ganirelix").
principio_attivo("gefitinib").
principio_attivo("gemcitabina").
principio_attivo("gemeprost").
principio_attivo("gemfibrozil").
principio_attivo("gentamicina").
principio_attivo("gestodene").
principio_attivo("glatiramer").
principio_attivo("glibenclamide").
principio_attivo("glicerolo").
principio_attivo("glicina").
principio_attivo("gliclazide").
principio_attivo("glicocorticoidi").
principio_attivo("glicopirronio").
principio_attivo("glicosidi").
principio_attivo("glimepiride").
principio_attivo("glucosamina").
principio_attivo("glucosio").
principio_attivo("glutatione").
principio_attivo("gonadorelina").
principio_attivo("gonadotropina").
principio_attivo("goserelin").
principio_attivo("granisetron").
principio_attivo("griseofulvina").
principio_attivo("guselkumab").
principio_attivo("hedera").
principio_attivo("hemophilus").
principio_attivo("ibritumomab").
principio_attivo("ibuprofen").
principio_attivo("ibuprofene").
principio_attivo("ibutilide").
principio_attivo("idarubicina").
principio_attivo("idebenone").
principio_attivo("idoxuridina").
principio_attivo("idroclorotiazide").
principio_attivo("idrocortisone").
principio_attivo("idrogeno").
principio_attivo("idrolisati").
principio_attivo("idromorfone").
principio_attivo("idrossicarbamide").
principio_attivo("idrossietil").
principio_attivo("idrossiprogesterone").
principio_attivo("idrossocobalamina").
principio_attivo("idursulfase").
principio_attivo("iloprost").
principio_attivo("imatinib").
principio_attivo("imecromone").
principio_attivo("imidazolo").
principio_attivo("imiglucerasi").
principio_attivo("imipenem").
principio_attivo("imipramina").
principio_attivo("imiquimod").
principio_attivo("immunoglobulina").
principio_attivo("immunoglobuline").
principio_attivo("indacaterol").
principio_attivo("indacaterolo").
principio_attivo("indapamide").
principio_attivo("indigo").
principio_attivo("indinavir").
principio_attivo("indobufene").
principio_attivo("indometacina").
principio_attivo("infliximab").
principio_attivo("influenza").
principio_attivo("ingenolo").
principio_attivo("inibitori").
principio_attivo("insetti").
principio_attivo("insulina").
principio_attivo("insuline").
principio_attivo("integratori").
principio_attivo("interferone").
principio_attivo("interferoni").
principio_attivo("iodio").
principio_attivo("iodio-123i-iobenguano").
principio_attivo("iodio-123i-ioflupano").
principio_attivo("iodio-131i-iobenguano").
principio_attivo("iodio-131i-sodioioduro").
principio_attivo("iodixanolo").
principio_attivo("iodopovidone").
principio_attivo("ioexolo").
principio_attivo("iomeprolo").
principio_attivo("iopamidolo").
principio_attivo("iopromide").
principio_attivo("ipecacuana").
principio_attivo("ipilimumab").
principio_attivo("ipratropio").
principio_attivo("irbesartan").
principio_attivo("irinotecan").
principio_attivo("isavuconazolo").
principio_attivo("isoconazolo").
principio_attivo("isoflurano").
principio_attivo("isoproterenolo").
principio_attivo("isosorbide").
principio_attivo("isotipendile").
principio_attivo("isotretinoina").
principio_attivo("isotretinoina,associazioni").
principio_attivo("ispaghula").
principio_attivo("isradipina").
principio_attivo("itraconazolo").
principio_attivo("ivabradina").
principio_attivo("ixazomib").
principio_attivo("josamicina").
principio_attivo("ketoconazolo").
principio_attivo("ketoprofene").
principio_attivo("ketorolac").
principio_attivo("ketotifene").
principio_attivo("labetalolo").
principio_attivo("lacidipina").
principio_attivo("lacosamide").
principio_attivo("lamivudina").
principio_attivo("lamotrigina").
principio_attivo("landiololo").
principio_attivo("lanreotide").
principio_attivo("lansoprazolo").
principio_attivo("laronidase").
principio_attivo("latanoprost").
principio_attivo("lattitolo").
principio_attivo("lattulosio").
principio_attivo("laurilsolfato").
principio_attivo("leflunomide").
principio_attivo("lenograstim").
principio_attivo("lercanidipina").
principio_attivo("lesinurad").
principio_attivo("letermovir").
principio_attivo("letrozolo").
principio_attivo("leuprolide").
principio_attivo("levetiracetam").
principio_attivo("levobunololo").
principio_attivo("levobupivacaina").
principio_attivo("levocarnitina").
principio_attivo("levocetirizina").
principio_attivo("levodopa").
principio_attivo("levodropropizina").
principio_attivo("levofloxacina").
principio_attivo("levomepromazina").
principio_attivo("levomethadone").
principio_attivo("levonorgestrel").
principio_attivo("levosimendano").
principio_attivo("levosulpiride").
principio_attivo("levotiroxina").
principio_attivo("levulosio").
principio_attivo("lidocaina").
principio_attivo("linagliptin").
principio_attivo("lincosamidi").
principio_attivo("linezolid").
principio_attivo("liotironina").
principio_attivo("liraglutide").
principio_attivo("lisinopril").
principio_attivo("litio").
principio_attivo("lixisenatide").
principio_attivo("lodoxamide").
principio_attivo("lofexidina").
principio_attivo("lomefloxacina").
principio_attivo("lomitapide").
principio_attivo("loperamide").
principio_attivo("lopinavir").
principio_attivo("loratadina").
principio_attivo("lorazepam").
principio_attivo("lormetazepam").
principio_attivo("lornoxicam").
principio_attivo("losartan").
principio_attivo("lovastatina").
principio_attivo("loxapina").
principio_attivo("lumacaftor").
principio_attivo("macitentan").
principio_attivo("macrogol").
principio_attivo("macrolidi").
principio_attivo("magaldrato").
principio_attivo("magnesio").
principio_attivo("maltolo").
principio_attivo("manidipina").
principio_attivo("mannitolo").
principio_attivo("mebendazolo").
principio_attivo("medrossiprogesterone").
principio_attivo("mefenesina").
principio_attivo("megestrolo").
principio_attivo("melevodopa").
principio_attivo("melfalan").
principio_attivo("meloxicam").
principio_attivo("memantina").
principio_attivo("mepartricina").
principio_attivo("mepivacaina").
principio_attivo("meprobamato").
principio_attivo("merbromina").
principio_attivo("mercaptamina").
principio_attivo("mercaptopurina").
principio_attivo("meropenem").
principio_attivo("mesalazina").
principio_attivo("mesna").
principio_attivo("metadone").
principio_attivo("metamizolo").
principio_attivo("metergolina").
principio_attivo("metformina").
principio_attivo("metildigossina").
principio_attivo("metildopa").
principio_attivo("metilergometrina").
principio_attivo("metilfenidato").
principio_attivo("metilnaltrexone").
principio_attivo("metilprednisolone").
principio_attivo("metiltioninio").
principio_attivo("metirapone").
principio_attivo("metixene").
principio_attivo("metoclopramide").
principio_attivo("metolazone").
principio_attivo("metoprololo").
principio_attivo("metossiflurano").
principio_attivo("metossipolietilenglicole-epoetina").
principio_attivo("metotrexato").
principio_attivo("metoxalene").
principio_attivo("metronidazolo").
principio_attivo("mianserina").
principio_attivo("micafungina").
principio_attivo("micofenolato").
principio_attivo("miconazolo").
principio_attivo("microsfere").
principio_attivo("midazolam").
principio_attivo("midodrina").
principio_attivo("mifamurtide").
principio_attivo("mifepristone").
principio_attivo("miglustat").
principio_attivo("minociclina").
principio_attivo("minoxidil").
principio_attivo("miocamicina").
principio_attivo("mirtazapina").
principio_attivo("misoprostolo").
principio_attivo("mitomicina").
principio_attivo("mitotane").
principio_attivo("mitoxantrone").
principio_attivo("mizolastina").
principio_attivo("moexipril").
principio_attivo("molsidomina").
principio_attivo("mometasone").
principio_attivo("montelukast").
principio_attivo("morbillo").
principio_attivo("morfina").
principio_attivo("morniflumato").
principio_attivo("moxifloxacina").
principio_attivo("moxonidina").
principio_attivo("mucolitici").
principio_attivo("multienzimi").
principio_attivo("mupirocina").
principio_attivo("nabiximols").
principio_attivo("nabumetone").
principio_attivo("nadifloxacin").
principio_attivo("nadroparina").
principio_attivo("nafazolina").
principio_attivo("naftidrofurile").
principio_attivo("naftifina").
principio_attivo("nalmefene").
principio_attivo("naloxegol").
principio_attivo("naloxone").
principio_attivo("naltrexone").
principio_attivo("naprossene").
principio_attivo("naproxene").
principio_attivo("nebivolol").
principio_attivo("nebivololo").
principio_attivo("nedocromile").
principio_attivo("nelarabina").
principio_attivo("neomicina").
principio_attivo("neostigmina").
principio_attivo("nepafenac").
principio_attivo("nepinalone").
principio_attivo("netilmicina").
principio_attivo("nevirapina").
principio_attivo("nicardipina").
principio_attivo("nicergolina").
principio_attivo("niclosamide").
principio_attivo("nicorandil").
principio_attivo("nicotina").
principio_attivo("nifedipina").
principio_attivo("nifuratel").
principio_attivo("nilotinib").
principio_attivo("nimesulide").
principio_attivo("nimodipina").
principio_attivo("niraparib").
principio_attivo("nisoldipina").
principio_attivo("nistatina").
principio_attivo("nitisinone").
principio_attivo("nitrati").
principio_attivo("nitrazepam").
principio_attivo("nitrendipina").
principio_attivo("nitrofurantoina").
principio_attivo("nitroglicerina").
principio_attivo("nitroprussiato").
principio_attivo("nivolumab").
principio_attivo("nomegestrol").
principio_attivo("noradrenalina").
principio_attivo("noretisterone").
principio_attivo("norfloxacina").
principio_attivo("nortriptilina").
principio_attivo("nusinersen").
principio_attivo("ocrelizumab").
principio_attivo("octreotide").
principio_attivo("ofatumumab").
principio_attivo("ofloxacina").
principio_attivo("oftalmologici").
principio_attivo("olanzapina").
principio_attivo("olaparib").
principio_attivo("olmesartan").
principio_attivo("olodaterolo").
principio_attivo("omalizumab").
principio_attivo("omatropina").
principio_attivo("omega-3-trigliceridi").
principio_attivo("omeprazolo").
principio_attivo("ondansetron").
principio_attivo("opicapone").
principio_attivo("orfenadrina").
principio_attivo("organismi").
principio_attivo("orlistat").
principio_attivo("oseltamivir").
principio_attivo("osimertinib").
principio_attivo("ospemifene").
principio_attivo("ossibuprocaina").
principio_attivo("ossibutinina").
principio_attivo("ossicodone").
principio_attivo("ossidrossido").
principio_attivo("ossigeno").
principio_attivo("ossimetazolina").
principio_attivo("ossitocina").
principio_attivo("ossitriptofano").
principio_attivo("otilonio").
principio_attivo("oxaliplatino").
principio_attivo("oxaprozina").
principio_attivo("oxcarbazepina").
principio_attivo("oxetacaina").
principio_attivo("oxicam-derivati").
principio_attivo("oxicodone").
principio_attivo("oxolamina").
principio_attivo("oxprenololo").
principio_attivo("oxycodone").
principio_attivo("ozenoxacina").
principio_attivo("paclitaxel").
principio_attivo("palifermina").
principio_attivo("paliperidone").
principio_attivo("palonosetron").
principio_attivo("pantoprazolo").
principio_attivo("papaverina").
principio_attivo("papillomavirus").
principio_attivo("paracalcitolo").
principio_attivo("paracetamolo").
principio_attivo("parnaparina").
principio_attivo("paromomicina").
principio_attivo("paroxetina").
principio_attivo("pefloxacina").
principio_attivo("pegaptanib").
principio_attivo("pegfilgrastim").
principio_attivo("peginterferone").
principio_attivo("pegloticasi").
principio_attivo("pegvisomant").
principio_attivo("pemetrexed").
principio_attivo("penciclovir").
principio_attivo("pentamidina").
principio_attivo("pentazocina").
principio_attivo("pentossiverina").
principio_attivo("peramivir").
principio_attivo("perampanel").
principio_attivo("pergolide").
principio_attivo("perindopril").
principio_attivo("permetrina").
principio_attivo("pertuzumab").
principio_attivo("petidina").
principio_attivo("picosolfato").
principio_attivo("picotamide").
principio_attivo("pidotimod").
principio_attivo("pigelina").
principio_attivo("pilocarpina").
principio_attivo("pimozide").
principio_attivo("pinazepam").
principio_attivo("pindololo").
principio_attivo("pioglitazone").
principio_attivo("piperacillina").
principio_attivo("piracetam").
principio_attivo("pirazinamide").
principio_attivo("pirfenidone").
principio_attivo("piridostigmina").
principio_attivo("piroxicam").
principio_attivo("pitavastatina").
principio_attivo("pivmecillinam").
principio_attivo("pixantrone").
principio_attivo("pizotifene").
principio_attivo("plerixafor").
principio_attivo("pneumococcus").
principio_attivo("policarbophyl").
principio_attivo("policresolsolfonato").
principio_attivo("polidocanolo").
principio_attivo("poliomielite").
principio_attivo("polistirensolfonato").
principio_attivo("polivitaminici").
principio_attivo("pomalidomide").
principio_attivo("potassio").
principio_attivo("pralidossima").
principio_attivo("pramipexolo").
principio_attivo("pramiracetam").
principio_attivo("pramocaina").
principio_attivo("pranoprofene").
principio_attivo("praparati").
principio_attivo("prasterone").
principio_attivo("pravastatina").
principio_attivo("prazepam").
principio_attivo("prednisolone").
principio_attivo("prednisone").
principio_attivo("pregabalin").
principio_attivo("prilocaina").
principio_attivo("primidone").
principio_attivo("procainamide").
principio_attivo("procinetici").
principio_attivo("progesterone").
principio_attivo("progestinici").
principio_attivo("proglumetacina").
principio_attivo("proguanil").
principio_attivo("promazina").
principio_attivo("prometazina").
principio_attivo("propafenone").
principio_attivo("propantelina").
principio_attivo("propifenazone").
principio_attivo("propionato").
principio_attivo("propiverina").
principio_attivo("propofol").
principio_attivo("propranololo").
principio_attivo("prostaglandine").
principio_attivo("protamina").
principio_attivo("protossido").
principio_attivo("prulifloxacina").
principio_attivo("pseudoefedrina").
principio_attivo("quetiapina").
principio_attivo("quinapril").
principio_attivo("rabeprazolo").
principio_attivo("racecadotril").
principio_attivo("radio-223").
principio_attivo("radiofarmaci").
principio_attivo("raloxifene").
principio_attivo("raltitrexed").
principio_attivo("ramipril").
principio_attivo("ramucirumab").
principio_attivo("ranitidina").
principio_attivo("rasagilina").
principio_attivo("reboxetina").
principio_attivo("regadenoson").
principio_attivo("remifentanil").
principio_attivo("repaglinide").
principio_attivo("repentina").
principio_attivo("reserpine").
principio_attivo("reslizumab").
principio_attivo("retapamulina").
principio_attivo("retigabina").
principio_attivo("retinolo").
principio_attivo("ribavirin").
principio_attivo("ribavirina").
principio_attivo("rifabutina").
principio_attivo("rifamicina").
principio_attivo("rifampicina").
principio_attivo("rifaximina").
principio_attivo("riluzolo").
principio_attivo("rimexolone").
principio_attivo("risedronic").
principio_attivo("risperidone").
principio_attivo("ritodrina").
principio_attivo("ritonavir").
principio_attivo("rivastigmina").
principio_attivo("rizatriptan").
principio_attivo("rocuronio").
principio_attivo("roflumilast").
principio_attivo("romiplostim").
principio_attivo("ropinirolo").
principio_attivo("ropivacaina").
principio_attivo("rosuvastatina").
principio_attivo("rotigotina").
principio_attivo("roxatidina").
principio_attivo("roxitromicina").
principio_attivo("rufinamide").
principio_attivo("rufloxacina").
principio_attivo("rupatadina").
principio_attivo("sacubitril").
principio_attivo("safinamide").
principio_attivo("salbutamol").
principio_attivo("salbutamolo").
principio_attivo("salmeterolo").
principio_attivo("sapropterina").
principio_attivo("saquinavir").
principio_attivo("saxagliptin").
principio_attivo("scopolamina").
principio_attivo("sebelipase").
principio_attivo("secretina").
principio_attivo("selegilina").
principio_attivo("selenio-75se-acido").
principio_attivo("selexipag").
principio_attivo("semaglutide").
principio_attivo("senna").
principio_attivo("sertralina").
principio_attivo("sevelamer").
principio_attivo("sevoflurano").
principio_attivo("sibutramina").
principio_attivo("sildenafil").
principio_attivo("siliconi").
principio_attivo("silimarina").
principio_attivo("silodosin").
principio_attivo("siltuximab").
principio_attivo("simeprevir").
principio_attivo("simpaticomimetici").
principio_attivo("simvastatina").
principio_attivo("sinecatechina").
principio_attivo("sitagliptin").
principio_attivo("sobrerolo").
principio_attivo("sodio").
principio_attivo("sofosbuvir").
principio_attivo("solifenacin").
principio_attivo("soluzioni").
principio_attivo("solventi").
principio_attivo("somatostatina").
principio_attivo("somatropina").
principio_attivo("sorafenib").
principio_attivo("sotalolo").
principio_attivo("spiramicina").
principio_attivo("spironolattone").
principio_attivo("sterculia").
principio_attivo("stronzio").
principio_attivo("sucralfato").
principio_attivo("sufentanil").
principio_attivo("sulfadiazina").
principio_attivo("sulfadimetoxina").
principio_attivo("sulfametoxazolo").
principio_attivo("sulfonamidi").
principio_attivo("sulodexide").
principio_attivo("sulpiride").
principio_attivo("sulprostone").
principio_attivo("sultamicillina").
principio_attivo("sumatriptan").
principio_attivo("sunitinib").
principio_attivo("surfattante").
principio_attivo("surfattanti").
principio_attivo("tacalcitolo").
principio_attivo("tacrolimus").
principio_attivo("tadalafil").
principio_attivo("talidomide").
principio_attivo("talimogene").
principio_attivo("tamoxifene").
principio_attivo("tamsulosin").
principio_attivo("tamsulosina").
principio_attivo("tapentadol").
principio_attivo("tecnezio-99mtc-acido").
principio_attivo("tecnezio-99mtc-anticorpo").
principio_attivo("tecnezio-99mtc-bicisato").
principio_attivo("tecnezio-99mtc-macrosalb").
principio_attivo("tecnezio-99mtc-mertiatide").
principio_attivo("tecnezio-99mtc-nanocolloide").
principio_attivo("tecnezio-99mtc-pertecnetato").
principio_attivo("tecnezio-99mtc-sestamibi").
principio_attivo("tecnezio-99mtc-tecnegas").
principio_attivo("tecnezio-99mtc-tetrofosmina").
principio_attivo("tecnezio-99mtc-tilmanocept").
principio_attivo("teduglutide").
principio_attivo("tegafur").
principio_attivo("teicoplanina").
principio_attivo("telaprevir").
principio_attivo("telavancina").
principio_attivo("telbivudina").
principio_attivo("telmisartan").
principio_attivo("temazepam").
principio_attivo("temoporfina").
principio_attivo("temozolomide").
principio_attivo("tenofovir").
principio_attivo("tenoxicam").
principio_attivo("teofillina").
principio_attivo("terazosina").
principio_attivo("terbinafina").
principio_attivo("teriparatide").
principio_attivo("terlipressina").
principio_attivo("terpeni").
principio_attivo("testosterone").
principio_attivo("tetraciclina").
principio_attivo("tetracicline").
principio_attivo("tetrizolina").
principio_attivo("tiagabina").
principio_attivo("tiamazolo").
principio_attivo("tiamfenicolo").
principio_attivo("tiamina").
principio_attivo("tiapride").
principio_attivo("tibenzonio").
principio_attivo("tibolone").
principio_attivo("ticlopidina").
principio_attivo("tifoideo").
principio_attivo("tigeciclina").
principio_attivo("tilactase").
principio_attivo("timololo").
principio_attivo("tinidazolo").
principio_attivo("tiocolchicoside").
principio_attivo("tioconazolo").
principio_attivo("tioguanina").
principio_attivo("tiosolfato").
principio_attivo("tiotropio").
principio_attivo("tirofiban").
principio_attivo("tiropramide").
principio_attivo("tirotricina").
principio_attivo("tirotropina").
principio_attivo("tivozanib").
principio_attivo("tizanidina").
principio_attivo("tobramicina").
principio_attivo("tocoferolo").
principio_attivo("tolterodina").
principio_attivo("tolvaptan").
principio_attivo("tonici").
principio_attivo("topiramato").
principio_attivo("topotecan").
principio_attivo("torasemide").
principio_attivo("tosilcloramide").
principio_attivo("tossoide").
principio_attivo("tramadolo").
principio_attivo("trandolapril").
principio_attivo("trastuzumab").
principio_attivo("travoprost").
principio_attivo("trazodone").
principio_attivo("treprostinil").
principio_attivo("tretinoina").
principio_attivo("triamcinolone").
principio_attivo("triazolam").
principio_attivo("trifluoperazina").
principio_attivo("trifluridina").
principio_attivo("triflusal").
principio_attivo("trimebutina").
principio_attivo("triptorelina").
principio_attivo("tromantadina").
principio_attivo("tropicamide").
principio_attivo("trospio").
principio_attivo("troxerutina").
principio_attivo("tuaminoeptano").
principio_attivo("ubidecarenone").
principio_attivo("ulipristal").
principio_attivo("umeclidino").
principio_attivo("urapidil").
principio_attivo("urofollitropina").
principio_attivo("urokinasi").
principio_attivo("vaccini").
principio_attivo("valaciclovir").
principio_attivo("valeriana").
principio_attivo("valganciclovir").
principio_attivo("valpromide").
principio_attivo("valsartan").
principio_attivo("vancomicina").
principio_attivo("vandetanib").
principio_attivo("vardenafil").
principio_attivo("vareniclina").
principio_attivo("vecuronio").
principio_attivo("vemurafenib").
principio_attivo("venlafaxina").
principio_attivo("verapamil").
principio_attivo("vernakalant").
principio_attivo("verteporfina").
principio_attivo("vigabatrina").
principio_attivo("vilanterol").
principio_attivo("vildagliptin").
principio_attivo("vinblastina").
principio_attivo("vincristina").
principio_attivo("vinflunina").
principio_attivo("vinorelbina").
principio_attivo("vismodegib").
principio_attivo("voriconazolo").
principio_attivo("vortioxetine").
principio_attivo("warfarin").
principio_attivo("xilometazolina").
principio_attivo("zafirlukast").
principio_attivo("zaleplon").
principio_attivo("zanamivir").
principio_attivo("zefenopril").
principio_attivo("ziconotide").
principio_attivo("zidovudina").
principio_attivo("ziprasidone").
principio_attivo("zofenopril").
principio_attivo("zolmitriptan").
principio_attivo("zolpidem").
principio_attivo("zonisamide").
principio_attivo("zopiclone").
