parola_chiave('trattamento').
parola_chiave('usato').
parola_chiave('impiegato').
parola_chiave('indicato').
parola_chiave('prescritto').
parola_chiave('serve').
parola_chiave('utilizzato').
parola_chiave('prevenire').
parola_chiave('previene').
parola_chiave('agisce').
parola_chiave('aiuta').
parola_chiave('ridurre').
parola_chiave('agisce').
